name: filter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.9
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - joblib=1.2.0
  - xgboost=1.7.4
  - pysam>=0.23.0