name: r_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.0
  - r-data.table
  - r-dplyr=1.1.4
  - r-ggplot2=3.4.4
  - r-readr=2.1.5
  - r-tidyr=1.3.1
  - r-stringr=1.5.1
  - r-purrr=1.0.2
  - r-optparse=1.7.4