name: Nextflow Test Pipeline Conda

on:
  push:
    branches:
      - test_actions
  pull_request:
    branches:
      - test_actions
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Apptainer
      uses: eWaterCycle/setup-apptainer@v2
      with:
        apptainer-version: 1.2.5
    
    - name: Cache Apptainer images
      uses: actions/cache@v4
      with:
        path: |
          ~/.apptainer/cache
          ${{ github.workspace }}/.apptainer
        key: apptainer-cache-${{ runner.os }}-${{ hashFiles('**/nextflow.config', '**/modules.config') }}
        restore-keys: |
          apptainer-cache-${{ runner.os }}-
    
    - name: Set up Apptainer cache directory
      run: |
        mkdir -p ${{ github.workspace }}/.apptainer
        export APPTAINER_CACHEDIR=${{ github.workspace }}/.apptainer
        echo "APPTAINER_CACHEDIR=${{ github.workspace }}/.apptainer" >> $GITHUB_ENV
    
    - name: Run Nextflow pipeline with Apptainer
      run: |
        nextflow run main.nf -profile test -with-apptainer
    
    - name: Check test completion and details
      run: |
        # Check if the test.passed file was created
        if [ ! -f "results/test/test.passed" ]; then
          echo "ERROR: Test completion file 'results/test/test.passed' not found"
          echo "Test pipeline did not complete successfully"
          exit 1
        fi
        
        echo "✅ Test completed successfully!"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nextflow-test-results
        path: |
          results/
          .nextflow.log
        retention-days: 7