name: Nextflow Test Pipeline Conda

on:
  push:
    branches:
      - test_actions
  pull_request:
    branches:
      - test_actions
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge,bioconda,defaults
        channel-priority: strict
    
    - name: Install Nextflow
      run: |
        curl -s https://get.nextflow.io | bash
        sudo mv nextflow /usr/local/bin/
        nextflow -version
    
    - name: Run Nextflow pipeline
      run: |
        nextflow run main.nf -profile test -with-conda

    - name: Check test completion and details
      run: |
        # Check if the test.passed file was created
        if [ ! -f "results/test/test.passed" ]; then
          echo "ERROR: Test completion file 'results/test/test.passed' not found"
          echo "Test pipeline did not complete successfully"
          exit 1
        fi
        
        echo "✅ Test completed successfully!"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nextflow-test-results
        path: |
          results/
          .nextflow.log
        retention-days: 7